In [1]:
import numpy as np
import scipy.sparse as ss
import scipy.sparse.linalg as ssl

In [11]:
A = np.array( [ [0,3,0] , [7,0,0] , [0,0,1] ] )
A, np.dot(A,A)

(array([[0, 3, 0],
        [7, 0, 0],
        [0, 0, 1]]),
 array([[21,  0,  0],
        [ 0, 21,  0],
        [ 0,  0,  1]]))

In [19]:
B = ss.csc_matrix( [ [0,3,0] , [7,0,0] , [0,0,1] ] )
B

<3x3 sparse matrix of type '<class 'numpy.int64'>'
	with 3 stored elements in Compressed Sparse Column format>

In [20]:
np.dot(B,B)

<3x3 sparse matrix of type '<class 'numpy.int64'>'
	with 3 stored elements in Compressed Sparse Column format>

In [21]:
B.toarray() , np.dot(B,B).toarray()

(array([[0, 3, 0],
        [7, 0, 0],
        [0, 0, 1]]),
 array([[21,  0,  0],
        [ 0, 21,  0],
        [ 0,  0,  1]]))

In [23]:
B_inv = ssl.inv(B)

In [29]:
%%timeit
np.dot(B,B_inv).toarray()

50.4 µs ± 1.63 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [30]:
%%timeit
B@B_inv.toarray()

4.83 µs ± 57 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [45]:
C = ss.csc_matrix( [ [4,-2,0,0] , [-2,4,-2,0] , [0,-2,4,-2] , [0,0,-2,4] ] )
D = ss.csc_matrix( [ [1,2,0,0] , [2,1,2,0] , [0,2,1,2] , [0,0,2,1] ] )
C.toarray(),D.toarray()

(array([[ 4, -2,  0,  0],
        [-2,  4, -2,  0],
        [ 0, -2,  4, -2],
        [ 0,  0, -2,  4]]),
 array([[1, 2, 0, 0],
        [2, 1, 2, 0],
        [0, 2, 1, 2],
        [0, 0, 2, 1]]))

In [46]:
Cinv = ssl.inv(C)
Mat = Cinv@D
Mat.toarray()

array([[1. , 1.5, 1. , 0.5],
       [1.5, 2. , 2. , 1. ],
       [1. , 2. , 2. , 1.5],
       [0.5, 1. , 1.5, 1. ]])

In [47]:
print(Mat)

  (3, 0)	0.49999999999999994
  (2, 0)	0.9999999999999999
  (1, 0)	1.4999999999999996
  (0, 0)	0.9999999999999998
  (3, 1)	1.0
  (2, 1)	2.0
  (1, 1)	1.9999999999999996
  (0, 1)	1.4999999999999998
  (3, 2)	1.5
  (2, 2)	2.0
  (1, 2)	1.9999999999999996
  (0, 2)	0.9999999999999998
  (3, 3)	1.0
  (2, 3)	1.5
  (1, 3)	0.9999999999999999
  (0, 3)	0.49999999999999994


In [48]:
print(C)

  (0, 0)	4
  (1, 0)	-2
  (0, 1)	-2
  (1, 1)	4
  (2, 1)	-2
  (1, 2)	-2
  (2, 2)	4
  (3, 2)	-2
  (2, 3)	-2
  (3, 3)	4
